#########################################################################
# File Name: make.sh
# Author: ma6174
# mail: ma6174@163.com
# Created Time: 四  6/21 16:15:12 2018
#########################################################################
#!/bin/bash
#./configure --enable-debug --prefix=/usr/local/php7 --enable-fpm && make && make install && sudo killall php-fpm&& sudo /usr/local/php7/sbin/php-fpm
#./configure --prefix=/usr/local/php7 --enable-fpm --enable-coro_http --enable-mysqlnd --enable-zip --with-pdo-mysql --with-openssl=/usr/local/Cellar/openssl/1.0.2o_2/ --enable-maintainer-zts --enable-opcache-file --with-curl && make && make install && sudo /usr/local/php7/sbin/php-fpm
#完整版mac
./configure --prefix=/usr/local/php7 --with-iconv=/usr/local/ --enable-fpm --enable-coro_http --enable-mysqlnd --enable-zip --with-pdo-mysql --with-openssl=/usr/local/Cellar/openssl/1.0.2o_2/ --enable-maintainer-zts --enable-opcache-file --with-curl --enable-bcmath --enable-calendar --enable-dba --enable-dtrace --enable-exif --enable-ftp --enable-intl --enable-mbregex --enable-mbstring --enable-pcntl --enable-phpdbg --enable-phpdbg-webhelper --enable-shmop --enable-soap --enable-sockets --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-wddx --enable-zip --with-bz2 --with-freetype-dir=/usr/local/Cellar/freetype/2.9.1/ --with-gd  --with-icu-dir=/usr/local/Cellar/icu4c/62.1/ --with-jpeg-dir=/usr/local/Cellar/jpeg/9c/ --with-kerberos --with-layout=GNU --with-ldap --with-ldap-sasl --with-libedit --with-libzip --with-mcrypt=/usr/local/Cellar/mcrypt/2.6.8/ --with-mhash --with-mysql-sockunixunix=/tmp/mysql.sock --with-mysqli=mysqlnd --with-ndbm --with-pdo-dblib=/usr/local/Cellar/freetds/1.00.92/ --with-pdo-mysql=mysqlnd --with-pdo-odbc=unixODBC,/usr/local/Cellar/unixodbc/2.3.6/ --with-pdo-pgsql=/usr/local/Cellar/libpq/10.4/ --with-pgsql=/usr/local/Cellar/libpq/10.4/ --with-pic --with-png-dir=/usr/local/Cellar/libpng/1.6.34/ --with-pspell=/usr/local/Cellar/aspell/0.60.6.1_1/ --with-unixODBC=/usr/local/Cellar/unixodbc/2.3.6/ --with-webp-dir=/usr/local/Cellar/webp/1.0.0/ --with-xmlrpc --with-xsl --with-zlib && make && make install && sudo /usr/local/php7/sbin/php-fpm
#完整版docker

./configure --prefix=/usr/local/php7  --enable-fpm --enable-coro_http --enable-mysqlnd --enable-zip --with-pdo-mysql --with-openssl --enable-maintainer-zts --enable-opcache-file --with-curl --enable-bcmath --enable-calendar  --enable-dtrace --enable-exif --enable-ftp  --enable-mbregex --enable-mbstring --enable-pcntl --enable-phpdbg --enable-phpdbg-webhelper --enable-shmop --enable-soap --enable-sockets --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-wddx  --with-bz2 --with-iconv --with-pic --with-xmlrpc  --with-mhash --with-mysql-sockunixunix=/tmp/mysql.sock --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --with-kerberos --with-layout=GNU   --with-mcrypt=/usr/include --with-gd --with-jpeg-dir=/usr/include --with-png-dir=/usr/include  --with-webp-dir=/usr/include --with-freetype-dir=/usr/include --with-icu-dir=/usr --with-pspell --with-xsl --with-libzip=/usr/local --enable-zip --with-zlib --with-pdo-dblib --with-pdo-odbc=unixODBC,/usr --with-unixODBC=/usr --with-libedit --enable-dba --with-ldap --with-ldap-sasl --with-pdo-pgsql --with-pgsql --with-gdbm --enable-intl --with-gettext && make && make install && make && make install && sudo /usr/local/php7/sbin/php-fpm
#./configure --enable-debug --prefix=/usr/local/php7 --enable-fpm && make && make install && sudo gdb /usr/local/php7/sbin/php-fpm
#./configure CFLAGS="-ggdb3" CXXFLAGS="-ggdb3" --prefix=/usr/local/php7 --enable-fpm --enable-coro_http --with-openssl --enable-maintainer-zts && make && make install && sudo gdb /usr/local/php7/sbin/php-fpm
